# .github/workflows/ci.yml

on:
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running workflow"
        env:
          SECRET: ${{ secrets.MY_SECRET }}
